# Generated by Django 5.0.7 on 2025-05-12 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=254, null=True)),
                ('domain', models.URLField(blank=True, max_length=254, null=True)),
                ('version', models.CharField(blank=True, max_length=25, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_details',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity_roles',
            },
        ),
        migrations.CreateModel(
            name='ModuleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=254, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.appdetails')),
            ],
            options={
                'db_table': 'app_module_details',
            },
        ),
        migrations.CreateModel(
            name='ComponentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(blank=True, max_length=254, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.appdetails')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.moduledetails')),
            ],
            options={
                'db_table': 'app_component_details',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.appdetails')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.componentdetails')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.moduledetails')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.roles')),
            ],
            options={
                'db_table': 'identity_role_permission',
            },
        ),
    ]
