# Generated by Django 5.0.7 on 2025-05-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(blank=True, max_length=25, unique=True)),
                ('department_name', models.CharField(blank=True, max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'department_details',
            },
        ),
    ]
