# Generated by Django 5.0.7 on 2025-05-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(blank=True, max_length=25, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=25, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('manager', models.CharField(blank=True, max_length=25)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('milestone', models.IntegerField(blank=True)),
                ('budget', models.IntegerField(blank=True)),
                ('resource_allocation_front_end', models.JSONField(blank=True, null=True)),
                ('resource_allocation_back_end', models.JSONField(blank=True, null=True)),
                ('resource_allocation_ba', models.JSONField(blank=True, null=True)),
                ('resource_allocation_tester', models.JSONField(blank=True, null=True)),
                ('resource_allocation_design', models.JSONField(blank=True, null=True)),
                ('resource_allocation_project_coordinator', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_details',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'team_details',
            },
        ),
    ]
